name: wadadak_design_system_example
description: 와다닥 디자인 시스템 컴포넌트 카탈로그.
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  wadadak_design_system:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/route.svg
